language: java
jdk:
  - oraclejdk8

install: ./gradlew clean jar
script: ./gradlew check

env:
  global:
    - PGP_KEY_ID="2887CE9B"
    - PGP_PASSWORD=""
    - PGP_SECRET_KEY_RING_FILE=~/.gnupg/secring.gpg
    - BINTRAY_USER=cjp39
    - BINTRAY_ORG=alicep-org
      # BINTRAY_KEY
    - secure: "GFIsdBY/eA1bbDVBU2RFSPJFm2Nu4tU99M90EJFhtoyAfJJKjulwjm3R9C+6gkXIznILbhnQea3GVokXgwOzzQMueBMIWqL5FaYXUF5mR1DMpCImV7nVBo26zc6UaPDPa2i6fjnsJa1+DAFhhr6xtdFJIiNeB7C6jLDrs/S8J2UMKfUVmZd1zId0ZPn3pa3jbdLeupDyPaMHwbCHBSGkInETlKkACfHvNTvoXyN4SlY+d4GvgC0+oh+0kie/M0GGl3/R/zG1Ry0SGvIuL8wctPEeNBP+MgaqyWrvi/9zkvZ6rRTtuEu+pRtcNJJKAQ2DYm+y4DqYKCwdeWN4G+A/oyGCiyvORB7uolCFanLo/8E3Rgz8XlDDzTwW1IFPvniLFIwIEtXtbk15/DcRC5y2Clcsy1jJnWTgMEDhCWtaXUf2iGcMJDO+MEO00t5S88OowSbIFFD3n/xxnuP9UTtoN7k6bmzJunIzThuWWPpOC8KAeyI0cMLfA9Rhs97lsFxCoySGgw/6hf5vcqVXlAh0Td+vRLqrXbdg9vHVW3sIhHN9yCsnxzTXlaP7H5dijFqL1gOLsl3OzvdQiTVLLbV8fREl+I2VeHSXJtAI6due4eqrURmBLknkszAmPuiAaEFLL8KWgnCNr6rY9rd/Bj0CuHTkZIrj1GxaSG2kZ20faR4="

deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew bintrayUpload --stacktrace --info
  on:
    tags: true
